name: H4CK UR LIFE
caption: and then patch it!
logo: /images/logo.png
default-image: https://gravatar.com/avatar/fceda72bc3836ad605642dad24b50797?s=500
markdown: redcarpet
pygments: true
url: http://blog.tunnelshade.in
