name: H4CK UR LIFE
caption: and then patch it!
logo: /images/logo.png
default-image: https://gravatar.com/avatar/fceda72bc3836ad605642dad24b50797?s=500
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
plugins: [jekyll-gist]
url: http://blog.tunnelshade.in
permalink: /:year/:month/:title.html
feeds: /atom.xml
future: true
